# Generated by Django 4.2.6 on 2024-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Automobiles', 'Automobiles'), ('Sports', 'Sports'), ('Clothing', 'Clothing')], default='Vegetables', max_length=25),
        ),
    ]
